# unless otherwise specified, hooks run on push only
default_stages: [pre-push]
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.28.4
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.8
    hooks:
      - id: uv-lock
  # formatters and linters are available in the virtualenv so they can be run from the makefile & vscode
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --force-exclude
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [python]
        require_serial: true
      - id: pyright
        name: pyright
        entry: uv run pyright
        # run on all files to catch type errors that affect unchanged files
        pass_filenames: false
        language: system
        types: [python]
      - id: test
        name: test
        entry: make test
        # run on all files
        pass_filenames: false
        language: system
        types: [python]
