services:
  up:
    build:
      context: .
      dockerfile: Dockerfile
      target: app

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    environment:
      - UP_TOKEN=${UP_TOKEN}
    command:
      - make
      - check
      - test-all

