services:
  up:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    environment:
      - UP_TOKEN=${UP_TOKEN}
      - ACTUAL__FILE=Mel
      - ACTUAL__ENCRYPTION_PASSWORD=${ACTUAL__ENCRYPTION_PASSWORD}
      - ACTUAL__PASSWORD=${ACTUAL__PASSWORD}
      - ACTUAL__URL=${ACTUAL__URL}

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    environment:
      - UP_TOKEN=${UP_TOKEN}
    command:
      - make
      - check
      - test-all
