name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  uv-python:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.x"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install the project
        run: make install
