name: Test in Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-in-docker:
    name: Test in Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Test All
        run: make test-all
        env:
          UP_TOKEN: ${{ secrets.UP_TOKEN }}
