name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-in-docker:
    name: Test in Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests in Docker
        run: docker compose run --build --rm test
        env:
          UP_TOKEN: ${{ secrets.UP_TOKEN }}
