name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  uv-python:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests in Docker
        run: docker compose run --build --rm test
